#!/usr/intel/pkgs/perl/5.26.1/bin/perl
use UsrIntel::R1;
use diagnostics;
use strict;

my @algorithms = ("IntelLVPMarchCExt", "IntelLVFailinjFx", "IntelLVAddrDecodeFx", "IntelLVAddrDecodeRowFastx", "IntelLVAddrDecodeRowOnlyFastx", "IntelLVArrayIFastx", "IntelLVArrayWriteFastx", "IntelLVGalColumnFastx", "IntelLVGalWRrecColFastx", "IntelLVHammer10Fastx", "IntelLVMarchCMinusFastx", "IntelLVMarchGFastx", "IntelLVMarchRAWFastx", "IntelLVMarchSLFastx", "IntelLVMatspDWOneFastx", "IntelLVMatspDWThreeFastx", "IntelLVMatspDWTwoFastx", "IntelLVMatsppFastx", "IntelLVScanFastx", "IntelLVSegSelFastx", "IntelLVButterflyFastx", "IntelLVMarchSRFastx", "IntelLVMarchSSFastx", "IntelLVButterflyWriteFastx", "IntelLVTowalk2Fastx", "SMarch", "IntelLVAddrDecodeColumnFastx", "IntelLVCellStrFastx", "IntelLVGalDiagFastx", "IntelLVHammerFastx", "IntelLVSlideDiagFx", "IntelLVSlideDiagFastxDiagEven", "IntelLVSlideDiagFastxRead", "IntelLVWalkColFastx", "IntelLVAddrDecodeFy", "IntelLVButterflyWriteFasty", "IntelLVGalWRrecRowFasty", "IntelLVHammer10Fasty", "IntelLVMarchCMinusFasty", "IntelLVMarchGFasty", "IntelLVMarchRAWFasty", "IntelLVMarchSLFasty", "IntelLVMatsppFasty", "IntelLVPMOVIFasty", "IntelLVScanFasty", "IntelLVAddrDecodeColumnFasty", "IntelLVAddrDecodeColumnOnlyFasty", "IntelLVAddrDecodeRowFasty", "IntelLVButterflyFasty", "IntelLVMarchSRFasty", "IntelLVMarchSSFasty", "IntelLVGalRowFasty", "IntelLVMatspFasty", "IntelLVSlidDiagStressFasty", "IntelLVTowalk2Fasty", "IntelLVWalkDiagFasty", "IntelLVWalkRowFasty", "IntelFIFAReadRecoveryFx_FIFA", "IntelFIFAWriteNOPTransitionFx_FIFA", "IntelFIFAWriteRecoveryFx_FIFA", "IntelFIFAWriteTransitionFx_FIFA", "IntelLVArrayReadLoopFx_FIFA", "IntelLVArrayWriteAndInverseLoopFx_FIFA", "IntelLVArrayWriteLoopFx_FIFA", "IntelLVArrayWriteReadLoopFx_FIFA", "IntelLVArrayDAddressRasterFx", "IntelLVPMOVIRasterFastx_NOCDP", "IntelLVPMOVIRasterFx_SAR", "IntelLVArrayRead10Fastx", "IntelLVArrayRead11Fastx", "IntelLVArrayReadFastx", "IntelLVArrayWrite10Fastx", "IntelLVArrayWrite11Fastx", "IntelWriteOneAddress", "IntelLVArrayWriteAddrRangeFx", "IntelLVPMOVIFastx");

foreach my $algorithm (@algorithms) {
  system("grep -rl \"Algorithm ($algorithm)\" $ENV{'MINT_PATH'}");
}
