./inputs/synthesis/upm/rtl/dftb_src/upm_ijtag_sib.vs
./inputs/synthesis/upm/rtl/dftb_src/upm_cutdc_dfx_db.vs
./inputs/synthesis/upm/rtl/dftb_src/upm_fdr_dfx_db.vs
./inputs/synthesis/upm/rtl/dftb_src/upm_dftb_ctech_map.sv
./inputs/synthesis/upm/rtl/dftb_src/upm_async_rst_metaflop_2_dfx_db.vs
./inputs/synthesis/upm/rtl/dftb_src/upm_metaflop_modeling.vs
./inputs/synthesis/upm/rtl/dftb_src/upm_dft_build_macros.vh
./inputs/synthesis/upm/rtl/dftb_src/upm_random_delay_dfx_db.vs
./inputs/synthesis/upm/rtl/dftb_src/upm_rtl2be_module.vs
./inputs/synthesis/upm/rtl/dftb_src/upm_rls_design_attributes.vs
./inputs/synthesis/upm/rtl/dteg_upm_top.sv
./inputs/synthesis/upm/rtl/upm_rtl/dteg_upm_top_apm_out.sv
./inputs/synthesis/upm/rtl/upm_rtl/upm_cbb_reg.vs
./inputs/synthesis/upm/rtl/upm_rtl/upm_cbb_control.sv
./inputs/synthesis/upm/rtl/upm_rtl/upm_apm_cbb_control.sv
./inputs/synthesis/upm/rtl/upm_rtl/upm_apm_cbb_reg.vs
./inputs/synthesis/upm/rtl/upm_rtl/upm_reg.vs
./inputs/synthesis/upm/rtl/upm_rtl/upm_reg_2.vs
./inputs/synthesis/upm/rtl/upm_rtl/upm_clk_divider.sv
./inputs/synthesis/upm/rtl/upm_rtl/upm_controller.sv
./inputs/synthesis/upm/rtl/upm_rtl/upm_counter.sv
./inputs/synthesis/upm/rtl/upm_rtl/upm_address_decoder.sv
./inputs/synthesis/upm/rtl/upm_rtl/upm_fabric.sv
./inputs/synthesis/upm/rtl/upm_rtl/upm_system_controller.sv
./inputs/synthesis/upm/rtl/upm_rtl/upm_system_cbb_pwren_decoder.sv
./inputs/synthesis/upm/rtl/upm_rtl/upm_cbb_control_2_cntrs.sv
./inputs/synthesis/upm/rtl/upm_rtl/upm_address_decoder_thermal.sv
./inputs/synthesis/upm/rtl/upm_rtl/upm_thermal_cbb_reg.vs
./inputs/synthesis/upm/rtl/upm_rtl/upm_cutmcp_mcr_pd_dftb.vs
./inputs/synthesis/upm/rtl/upm_rtl/upm_fdr_mcr_dftb.vs
./inputs/synthesis/upm/rtl/cbb_configs/cbb_permutation/cbb_wrapper_top.sv
./inputs/synthesis/upm/rtl/cbb_configs/cbb_permutation/cbb_wrapper_top_apm_out.sv
./inputs/synthesis/upm/rtl/cbb_configs/cbb_permutation/cbb_1/upm_cbb_wrapper_cbb_1_top.sv
./inputs/synthesis/upm/rtl/cbb_configs/cbb_permutation/cbb_2/upm_cbb_wrapper_cbb_2_top.sv
./inputs/synthesis/upm/rtl/cbb_configs/cbb_permutation/cbb_3/upm_cbb_wrapper_cbb_3_top.sv
./inputs/synthesis/upm/rtl/cbb_configs/cbb_permutation/cbb_4/upm_cbb_wrapper_cbb_4_top.sv
./inputs/synthesis/upm/rtl/cbb_configs/cbb_permutation/cbb_8/upm_cbb_wrapper_cbb_8_top.sv
./inputs/synthesis/upm/rtl/cbb_configs/cbb_permutation/common/upm_cbb_wrapper_cbb_1.vs
./inputs/synthesis/upm/rtl/cbb_configs/cbb_permutation/common/upm_cbb_wrapper_cbb_n.vs
./inputs/synthesis/upm/rtl/cbb_configs/cbb_permutation/common/upm_cbb_wrapper_cbb_o.vs
./inputs/synthesis/upm/rtl/cbb_configs/cbb_permutation/apm/upm_cbb_wrapper_asensor.sv
./inputs/synthesis/upm/rtl/cbb_configs/cbb_permutation/apm/upm_cbb_wrapper_ip78xanasensor.vs
./inputs/synthesis/upm/rtl/cbb_configs/cbb_permutation/apm/upm_cbb_wrapper_asensor_out.sv
./inputs/synthesis/upm/rtl/cbb_configs/cbb_permutation/apm/upm_cbb_wrapper_ip78xanasensor_out.vs
./inputs/synthesis/upm/rtl/cbb_configs/cbb_permutation/thermal/upm_cbb_wrapper_thermal_top.sv
./inputs/synthesis/upm/rtl/cbb_configs/cbb_permutation/thermal/upm_thermal_n.vs  
./inputs/synthesis/upm/rtl/cbb_configs/cbb_permutation/thermal/upm_thermal_o.vs
